
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: CART-SERVICE


  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/HuyShop
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

server:
  port: 8083

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
